apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  namespace: demo-helloworld-app
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image:
            reg.vipex.cc:80/k8s/nginx:alpine
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: stg
              mountPath: /stg
          workingDir: /stg
      restartPolicy: Always
      volumes:
        - name: stg
          hostPath:
            path: /stg
            type: DirectoryOrCreate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-srv
  namespace: demo-helloworld-app
  labels:
    app: helloworld
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: helloworld

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ing
  namespace: demo-helloworld-app
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: helloworld
spec:
  rules:
    - host: ngx.local
      http:
        paths:
          - backend:
              service:
                name: helloworld-srv
                port:
                  number: 80
            path: /
            pathType: Prefix
